### ISSUE TITLE
chore: 스토리북 도입

### ISSUE THREAD

**Issue by lurgi** [Daily-Drip-Dev/Driply#2]
Bottom-Up 방식 구현에서 스토리북이 없으니 시각적으로 피드백을 받을 마땅한 방법이 없다고 느껴졌어요.
그래서 스토리북 도입하는 걸 제안드려요

### Remix에서 외부 도구를 사용하는 방법
https://remix.run/docs/en/main/guides/vite#plugin-usage-with-other-vite-based-tools-eg-vitest-storybook

**Comment by lurgi** [comment]
https://remix.run/docs/en/main/guides/vite#plugin-usage-with-other-vite-based-tools-eg-vitest-storybook

**Comment by llqqssttyy** [comment]
찬성합니다. 적당한 Storybook 사용은 오히려 빠르게 실험하고 피드백 주기를 짧게 가져가기에 유리하다고 생각해요~
