### ISSUE TITLE
feat: Supabase 테이블 추가

### ISSUE THREAD

**Issue by llqqssttyy** [Daily-Drip-Dev/Driply#3]
- [2025.02.14] 업데이트
  - USER 테이블 제거

## 데이터베이스 컨벤션

이번 작업하면서 사용할 컨벤션입니다. 필요할 때마다 추가해보아요~

### 네이밍 컨벤션
- 테이블 이름은 단수형을 사용한다.
  - 테이블 이름은 엔티티를 표현하므로 단수형을 사용한다.
  - 예: `user`, `coffee`
- 테이블 이름과 컬럼 이름은 모두 snake case를 사용한다.
  - 예: `auth_token`
- 외래키(foreign key)는 참조하는 `테이블 이름 + '_'`를 사용한다.
  - 예: `user_id`, `coffee_id`
- boolean 컬럼은 `is_`나 `has_` 접두사를 붙인다.

## Entity 미리 보기

- 각 엔티티의 id는 지난 회의 때 uuid로 설정했는데 uuid와 int8 primary key의 크기 차이가 꽤 많이 나서(4배) primary key로 모두 변경합니다.
- 조사해 보니 uuid로 설정하는 건 분산 데이터베이스에 유용하다네요.

### Coffee

필드 이름 | 설명 | 데이터 타입 | 비고
-- | -- | -- | --
id | 커피 기록 고유 ID | INT8 | 기본 키로 사용하며 자동 증가 (Primary Key).
user_id | 종속된 유저 | fk | User 테이블과 관계형 설계
title | 커피 이름 | TEXT | 커피 이름은 짧은 텍스트. 255자로 제한.
sweetness | 단맛 점수 | NUMERIC(2, 1) | 0~10 점수로 가정, 소수점 한 자리까지 허용.
acidity | 산미 점수 | NUMERIC(2, 1) | 동일한 점수 형태로 처리.
fragrance | 향 점수 | NUMERIC(2, 1) | 동일한 점수 형태로 처리.
balance | 밸런스 점수 | NUMERIC(2, 1) | 동일한 점수 형태로 처리.
score | 전반적인 인상 | NUMERIC(2, 1) | 동일한 점수 형태로 처리.
img_url | 이미지 URL | TEXT | URL 길이에 제한이 없으므로 일단 text로 할 예정

### ~~User~~(Deprecated)

필드 이름 | 설명 | 데이터 타입 | 비고
-- | -- | -- | --
id | 유저 고유 ID | UUID | 기본 키로 사용하며 자동 증가 (Primary Key).
username | 사용자 이름 (고유 값) | VARCHAR(50) | 사용자 이름은 일반적으로 짧고 고유하므로 인덱스를 추가.
email | 사용자 계정 (고유 값) | VARCHAR(255) | 추후 OAuth 로그인 구현 시 필요한 필드입니다.

**Comment by lurgi** [comment]
정리해주셔서 감사해요! 테이블 만들어 주셔서 한눈에 넘 보기 좋습니당! 👍

- coffeelogs 네이밍을 coffees 혹은 coffeeList등 예상가능한 네이밍으로 변경하는건 어떨까요? log는 비지니스 도메인 용어로 생각되는데요, **사용하는 개발자 입장에서 coffeelogs라는 이름이 떠오르진 않을 것 같아용.**
- 혹은 Coffee 모델의 이름을 CoffeeLog로 변경하는 것도 괜찮아 보여요!

**Comment by llqqssttyy** [comment]
@lurgi 
좋아요~ 이름은 일단 회의록에 있던 네이밍을 박아둔 거고, 좋은 네이밍에 대해서 고민 중이었습니다! 
- coffeelogs -> 저는 `coffee_list` 정도가 괜찮을 것 같아요.
- Coffee 모델 -> 말씀하신대로 log는 비즈니스 용어라서 언제든 변경될 수 있기에 CoffeeLog보단 그냥 Coffee가 낫다고 생각합니다.

**Comment by llqqssttyy** [comment]
@lurgi 
- 외래키에 대해서 더 조사해 보니 현재 상황에서는 Coffee쪽에만 외래키를 만들면 되더라구요~ 그래서 user table 쪽 coffeelogs column은 빠지게 되었습니다.
- GraphQL 스키마는 다음과 같이 작성하면 된대요.(GPT)

```js
type User {
  id: ID!
  name: String!
  coffees: [Coffee!]! # User에 연결된 Coffee 리스트
}

type Coffee {
  id: ID!
  userId: ID!
  name: String!
  description: String
}

type Query {
  user(id: ID!): User
  coffeesByUser(userId: ID!): [Coffee!]!
}

```

**Comment by llqqssttyy** [comment]
@lurgi 

## 외래키 액션
Coffee 테이블은 User 테이블과 외래키(`user_id`)로 연결되어 있어요. 이때 **외래키가 참조하는 데이터가 변경되거나 삭제될 때, 그에 따라 어떤 동작을 할지를 정의**해야 합니다. 의사결정 해야 할 건 두 가지에요. 정책적인 부분이라 함께 고민해봐야 할 것 같습니다.

1. soft delete vs hard delete
User가 삭제되었을 때 어떻게 처리하느냐에 따라서 액션을 부여할 수 있는데요, 유저 정보와 커피 기록 정보를 soft delete해서 실제 DB에는 데이터를 남겨둘지, 아니면 완전히 삭제하는 hard delete로 관리할지 결정해야 합니다. 

2. action 정의
- soft delete로 관리한다면: 아무것도 안해도 됨(대신 쿼리문에 조건이 하나 추가되어야 함)
- 유저 삭제 시 관련 커피 데이터도 삭제해야 한다면: CASCADE
- 커피 데이터는 유저 없이도 유지돼야 한다면: SET NULL

---
제 의견은, 현재는 MVP 단계니까 Hard Delete로 처리하고 CASCADE 액션을 추가하는 게 어떨까 합니다.

**Comment by lurgi** [comment]
저도 hard delete가 적절하다 생각됩니다. DB용량 측면에서 초기 비용을 발생시키지 않을 수 있다 생각되어요.
궁금한 점은, hard delete시 Storage에 있는 이미지도 함께 삭제할 수 있게 설정이 필요할 거란 생각이네용!
짱짱

**Comment by llqqssttyy** [comment]
오호 그 부분은 따로 storage 설정하면서 따로 알아보겠습니다! 짱짱

**Comment by lurgi** [comment]
아맞당 그리구 createAt과 updatedAt은 기본적으로 포함인건가용?

**Comment by llqqssttyy** [comment]
created_at은 데이터가 생성되면 기본으로 생성되고, Coffee 테이블의 경우 updated_at은 기본값으로 들어가지 않고 있어요.

**Comment by lurgi** [comment]
@llqqssttyy coffee 테이블에 place에 관련된 정보가 추가되면 좋겠어요~ 
저는 **is_self라는 속성과 naver_place_id 두 개의 속성이 필요**하다 생각해요

현재 직접 내린 커피에 대한 기록은 '홈카페'라는 문구를,
네이버 플레이스를 연동한다면 '가게 이름'을 나타내고 싶은데요, 
따라서 네이버 플레이스 ID값과 홈카페 여부를 판단해야할 것으로 보여요.
네이버 장소가 자주 업데이트되기 때문에,is_self와 naver_place_id 둘 다 필요하다 생각합니다!
